Spec_Nav/urls.py
from django.contrib import admin
from django.urls import path,include
import food,shopping

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/',include('food.urls')),
    path('shopping/',include('shopping.urls')),
]

food/urls.py
from django.urls import path
from food.views import *

app_name = 'food'

urlpatterns = [
    path('nonveg/',nonveg,name='nonveg'),
]

shopping/urls.py
from django.urls import path
from shopping.views import *

app_name = 'shopping'

urlpatterns = [
    path('suite/',suite,name='suite')
]

food/models.py
from django.db import models

# Create your models here.

shopping/models.py
from django.db import models

# Create your models here.

food/views.py
from django.shortcuts import render

# Create your views here.


def nonveg(request):
    return render(request,'nonveg.html')

shopping/views.py
from django.shortcuts import render

# Create your views here.


def suite(request):
    return render(request,'suite.html')

templates/nonveg.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Nonveg</title>
</head>
<body>
    <center>
        <h1>
            This is nonveg page
        </h1>
        <a href="{% url 'shopping:suite' %}">Go to shopping page</a>
    </center>
</body>
</html>

templates/suite.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>suite</title>
</head>
<body>
    <center>
        <h1>
            here we have suites
        </h1>
        <a href="{% url 'food:nonveg' %}">Go to food page</a>
    </center>
</body>
</html>